var hierarchy =
[
    [ "__itt_domain", "struct____itt__domain.html", null ],
    [ "__itt_null_t", "struct____itt__null__t.html", null ],
    [ "__itt_string_handle", "struct____itt__string__handle.html", null ],
    [ "bdm::BaseBiologyModule", "structbdm_1_1BaseBiologyModule.html", [
      [ "bdm::GrowDivide", "structbdm_1_1GrowDivide.html", null ],
      [ "bdm::NullBiologyModule", "structbdm_1_1NullBiologyModule.html", null ],
      [ "bdm::RegulateGenes", "structbdm_1_1RegulateGenes.html", null ]
    ] ],
    [ "bdm::BiologyModuleOp", "structbdm_1_1BiologyModuleOp.html", null ],
    [ "bdm::BoundSpace", "classbdm_1_1BoundSpace.html", null ],
    [ "bdm::Grid< TSimulation >::Box", "structbdm_1_1Grid_1_1Box.html", null ],
    [ "bdm::Capsule< TSoExt >", "structbdm_1_1Capsule.html", null ],
    [ "bdm::experimental::neuroscience::Capsule< TSoExt >", "structbdm_1_1experimental_1_1neuroscience_1_1Capsule.html", null ],
    [ "bdm::Capsule< CellExt >", "structbdm_1_1Capsule_3_01CellExt_01_4.html", null ],
    [ "bdm::experimental::neuroscience::Capsule< NeuriteElementExt >", "structbdm_1_1experimental_1_1neuroscience_1_1Capsule_3_01NeuriteElementExt_01_4.html", null ],
    [ "bdm::experimental::neuroscience::Capsule< NeuronSomaExt >", "structbdm_1_1experimental_1_1neuroscience_1_1Capsule_3_01NeuronSomaExt_01_4.html", null ],
    [ "bdm::CatalystAdaptor< TSimulation >", "classbdm_1_1CatalystAdaptor.html", null ],
    [ "bdm::CellDivisionEvent", "structbdm_1_1CellDivisionEvent.html", null ],
    [ "bdm::CircularBuffer< T, N >", "classbdm_1_1CircularBuffer.html", null ],
    [ "bdm::CommandLineOptions", "structbdm_1_1CommandLineOptions.html", null ],
    [ "bdm::CommitOp", "classbdm_1_1CommitOp.html", null ],
    [ "bdm::CompileTimeParam< TBackend >", "structbdm_1_1CompileTimeParam.html", null ],
    [ "bdm::Constant", "structbdm_1_1Constant.html", null ],
    [ "bdm::detail::ConvertToContainerTuple< Backend, Types >", "structbdm_1_1detail_1_1ConvertToContainerTuple.html", null ],
    [ "bdm::ConvertToContainerTuple< Backend, TCTList >", "structbdm_1_1ConvertToContainerTuple.html", null ],
    [ "bdm::detail::ConvertToContainerTuple< Backend, CTList< Types...> >", "structbdm_1_1detail_1_1ConvertToContainerTuple_3_01Backend_00_01CTList_3_01Types_8_8_8_4_01_4.html", null ],
    [ "bdm::ConvertToContainerTuple< Backend, Types >", "structbdm_1_1ConvertToContainerTuple.html", null ],
    [ "bdm::CTList< Types >", "structbdm_1_1CTList.html", null ],
    [ "bdm::DefaultCTParam< TBackend >::CTMap< TSimObject, Dummy >", "structbdm_1_1DefaultCTParam_1_1CTMap.html", null ],
    [ "bdm::experimental::neuroscience::DefaultCTParam< TBackend >::CTMap< TSimObject, Dummy >", "structbdm_1_1experimental_1_1neuroscience_1_1DefaultCTParam_1_1CTMap.html", null ],
    [ "bdm::CTMapDefault< TSimObject, Dummy >", "structbdm_1_1CTMapDefault.html", null ],
    [ "bdm::CTMapDefault< Cell, Dummy >", "structbdm_1_1CTMapDefault.html", [
      [ "bdm::DefaultCTParam< TBackend >::CTMap< Cell, Dummy >", "structbdm_1_1DefaultCTParam_1_1CTMap_3_01Cell_00_01Dummy_01_4.html", null ]
    ] ],
    [ "bdm::DefaultCTParam< TBackend >", "structbdm_1_1DefaultCTParam.html", null ],
    [ "bdm::experimental::neuroscience::DefaultCTParam< TBackend >", "structbdm_1_1experimental_1_1neuroscience_1_1DefaultCTParam.html", null ],
    [ "bdm::DefaultForce", "classbdm_1_1DefaultForce.html", null ],
    [ "bdm::DiffusionGrid", "classbdm_1_1DiffusionGrid.html", null ],
    [ "bdm::DiffusionOp", "classbdm_1_1DiffusionOp.html", null ],
    [ "bdm::DisplacementOp< TSimulation >", "classbdm_1_1DisplacementOp.html", null ],
    [ "bdm::DisplacementOp< bdm::Simulation >", "classbdm_1_1DisplacementOp.html", null ],
    [ "bdm::DisplacementOpCpu< TSimulation >", "classbdm_1_1DisplacementOpCpu.html", null ],
    [ "bdm::DisplacementOpCuda< TSimulation >", "classbdm_1_1DisplacementOpCuda.html", null ],
    [ "bdm::DisplacementOpCudaKernel", "classbdm_1_1DisplacementOpCudaKernel.html", null ],
    [ "bdm::DisplacementOpOpenCL< TSimulation >", "classbdm_1_1DisplacementOpOpenCL.html", null ],
    [ "bdm::DividingCellOp", "classbdm_1_1DividingCellOp.html", null ],
    [ "bdm::Exporter< TContainer >", "classbdm_1_1Exporter.html", [
      [ "bdm::BasicExporter< TContainer >", "classbdm_1_1BasicExporter.html", null ],
      [ "bdm::MatlabExporter< TContainer >", "classbdm_1_1MatlabExporter.html", null ],
      [ "bdm::NeuroMLExporter< TContainer >", "classbdm_1_1NeuroMLExporter.html", null ],
      [ "bdm::ParaviewExporter< TContainer, TSimulation >", "classbdm_1_1ParaviewExporter.html", null ]
    ] ],
    [ "bdm::ExporterFactory", "classbdm_1_1ExporterFactory.html", null ],
    [ "bdm::FixedSizeVector< T, N >", "classbdm_1_1FixedSizeVector.html", null ],
    [ "bdm::FixedSizeVector< const bdm::Grid::Box *, 27 >", "classbdm_1_1FixedSizeVector.html", null ],
    [ "bdm::GaussianBand", "structbdm_1_1GaussianBand.html", null ],
    [ "bdm::detail::GetIndexImpl< T, Counter, Types >", "structbdm_1_1detail_1_1GetIndexImpl.html", null ],
    [ "bdm::detail::GetIndexImpl< T, Counter, FirstType >", "structbdm_1_1detail_1_1GetIndexImpl_3_01T_00_01Counter_00_01FirstType_01_4.html", null ],
    [ "bdm::detail::GetIndexImpl< T, Counter, FirstType, RemainingTypes...>", "structbdm_1_1detail_1_1GetIndexImpl_3_01T_00_01Counter_00_01FirstType_00_01RemainingTypes_8_8_8_4.html", null ],
    [ "bdm::Grid< TSimulation >", "classbdm_1_1Grid.html", null ],
    [ "bdm::Grid< bdm::Simulation >", "classbdm_1_1Grid.html", null ],
    [ "bdm::InlineVector< T, N >", "classbdm_1_1InlineVector.html", null ],
    [ "bdm::InSituPipeline", "classbdm_1_1InSituPipeline.html", null ],
    [ "bdm::IntegralTypeWrapper< T >", "classbdm_1_1IntegralTypeWrapper.html", null ],
    [ "bdm::is_soa< Backend >", "structbdm_1_1is__soa.html", null ],
    [ "bdm::is_soa_sphere< TSimObject >", "structbdm_1_1is__soa__sphere.html", null ],
    [ "bdm::Grid< TSimulation >::Box::Iterator", "structbdm_1_1Grid_1_1Box_1_1Iterator.html", null ],
    [ "bdm::Log", "classbdm_1_1Log.html", null ],
    [ "bdm::Math", "structbdm_1_1Math.html", null ],
    [ "bdm::ModelInitializer", "structbdm_1_1ModelInitializer.html", null ],
    [ "bdm::Grid< TSimulation >::NeighborIterator", "structbdm_1_1Grid_1_1NeighborIterator.html", null ],
    [ "bdm::experimental::neuroscience::NeuriteBifurcationEvent", "structbdm_1_1experimental_1_1neuroscience_1_1NeuriteBifurcationEvent.html", null ],
    [ "bdm::experimental::neuroscience::NeuriteBranchingEvent", "structbdm_1_1experimental_1_1neuroscience_1_1NeuriteBranchingEvent.html", null ],
    [ "bdm::experimental::neuroscience::NeuronNeuriteAdapter< TNeuronSomaSoPtr, TNeuriteElementSoPtr >", "classbdm_1_1experimental_1_1neuroscience_1_1NeuronNeuriteAdapter.html", null ],
    [ "bdm::experimental::neuroscience::NewNeuriteExtensionEvent", "structbdm_1_1experimental_1_1neuroscience_1_1NewNeuriteExtensionEvent.html", null ],
    [ "bdm::OneElementArray< T >", "classbdm_1_1OneElementArray.html", null ],
    [ "Op", null, [
      [ "bdm::VTuneOpWrapper< Op >", "classbdm_1_1VTuneOpWrapper.html", null ]
    ] ],
    [ "bdm::OpTimer< TOp >", "structbdm_1_1OpTimer.html", null ],
    [ "bdm::OpTimer< bdm::BiologyModuleOp >", "structbdm_1_1OpTimer.html", null ],
    [ "bdm::OpTimer< bdm::BoundSpace >", "structbdm_1_1OpTimer.html", null ],
    [ "bdm::OpTimer< bdm::CommitOp >", "structbdm_1_1OpTimer.html", null ],
    [ "bdm::OpTimer< bdm::DiffusionOp >", "structbdm_1_1OpTimer.html", null ],
    [ "bdm::OpTimer< bdm::DisplacementOp< bdm::Simulation > >", "structbdm_1_1OpTimer.html", null ],
    [ "bdm::OpTimer< bdm::DisplacementOp< TSimulation > >", "structbdm_1_1OpTimer.html", null ],
    [ "bdm::Param", "structbdm_1_1Param.html", null ],
    [ "bdm::experimental::neuroscience::Param", "structbdm_1_1experimental_1_1neuroscience_1_1Param.html", null ],
    [ "bdm::PoissonBand", "structbdm_1_1PoissonBand.html", null ],
    [ "bdm::Random", "classbdm_1_1Random.html", null ],
    [ "bdm::detail::ReadContainerFunctor< TSoSimBackend, TBackend >", "structbdm_1_1detail_1_1ReadContainerFunctor.html", null ],
    [ "bdm::ResourceManager< TCompileTimeParam >", "classbdm_1_1ResourceManager.html", null ],
    [ "bdm::ResourceManager< TCTParam >", "classbdm_1_1ResourceManager.html", null ],
    [ "bdm::RuntimeVariables", "classbdm_1_1RuntimeVariables.html", null ],
    [ "bdm::RunVisitor< TSimulationObject >", "structbdm_1_1RunVisitor.html", null ],
    [ "bdm::Scalar", "structbdm_1_1Scalar.html", null ],
    [ "bdm::ScalarSimulationObject< TCompileTimeParam, TDerived >", "classbdm_1_1ScalarSimulationObject.html", null ],
    [ "bdm::Scheduler< TSimulation >", "classbdm_1_1Scheduler.html", null ],
    [ "bdm::Scheduler< bdm::Simulation >", "classbdm_1_1Scheduler.html", null ],
    [ "bdm::experimental::neuroscience::SideNeuriteExtensionEvent", "structbdm_1_1experimental_1_1neuroscience_1_1SideNeuriteExtensionEvent.html", null ],
    [ "bdm::Simulation< TCTParam >", "structbdm_1_1Simulation.html", null ],
    [ "bdm::SimulationBackup", "classbdm_1_1SimulationBackup.html", null ],
    [ "bdm::SimulationObjectImpl< TCompileTimeParam, TDerived >", "structbdm_1_1SimulationObjectImpl.html", null ],
    [ "bdm::SimulationObjectVector< T, TSimulation >", "classbdm_1_1SimulationObjectVector.html", null ],
    [ "bdm::SimulationObjectVector< bdm::SoHandle, bdm::Simulation >", "classbdm_1_1SimulationObjectVector.html", null ],
    [ "bdm::SimulationObjectVector< bdm::SoHandle, TSimulation >", "classbdm_1_1SimulationObjectVector.html", null ],
    [ "bdm::Soa", "structbdm_1_1Soa.html", null ],
    [ "bdm::SoaRef", "structbdm_1_1SoaRef.html", null ],
    [ "bdm::SoaSimulationObject< TCompileTimeParam, TDerived >", "classbdm_1_1SoaSimulationObject.html", null ],
    [ "bdm::SoHandle", "classbdm_1_1SoHandle.html", null ],
    [ "bdm::SoPointer< TSoSimBackend, TBackend >", "classbdm_1_1SoPointer.html", null ],
    [ "bdm::experimental::neuroscience::SplitNeuriteElementEvent", "structbdm_1_1experimental_1_1neuroscience_1_1SplitNeuriteElementEvent.html", null ],
    [ "bdm::StreamerReadFunctor< TVariant >", "structbdm_1_1StreamerReadFunctor.html", null ],
    [ "bdm::StreamerWriteFunctor< Types >", "structbdm_1_1StreamerWriteFunctor.html", null ],
    [ "TBase", null, [
      [ "bdm::CellExt< TCompileTimeParam, TDerived, TBase >", "classbdm_1_1CellExt.html", null ],
      [ "bdm::experimental::neuroscience::NeuriteElementExt< TCompileTimeParam, TDerived, TBase >", "classbdm_1_1experimental_1_1neuroscience_1_1NeuriteElementExt.html", null ],
      [ "bdm::experimental::neuroscience::NeuronSomaExt< TCompileTimeParam, TDerived, TBase >", "classbdm_1_1experimental_1_1neuroscience_1_1NeuronSomaExt.html", null ]
    ] ],
    [ "bdm::TFileRaii", "classbdm_1_1TFileRaii.html", null ],
    [ "bdm::Timing", "classbdm_1_1Timing.html", null ],
    [ "bdm::TimingAggregator", "classbdm_1_1TimingAggregator.html", null ],
    [ "bdm::detail::ToIndex< TSo, Types >", "structbdm_1_1detail_1_1ToIndex.html", null ],
    [ "bdm::detail::ToIndex< TSo, CTList< Types...> >", "structbdm_1_1detail_1_1ToIndex_3_01TSo_00_01CTList_3_01Types_8_8_8_4_01_4.html", null ],
    [ "bdm::TransactionalVector< T >", "classbdm_1_1TransactionalVector.html", null ],
    [ "type", null, [
      [ "bdm::SimulationObject< TCompileTimeParam, TDerived >", "classbdm_1_1SimulationObject.html", null ]
    ] ],
    [ "bdm::type_ternary_operator< Condition, T, U >", "structbdm_1_1type__ternary__operator.html", null ],
    [ "bdm::type_ternary_operator<false, T, U >", "structbdm_1_1type__ternary__operator_3false_00_01T_00_01U_01_4.html", null ],
    [ "bdm::type_ternary_operator<is_same< Backend, bdm::SoaRef >::value, size_t &, size_t >", "structbdm_1_1type__ternary__operator.html", null ],
    [ "bdm::type_ternary_operator<is_same< Backend, bdm::SoaRef >::value, std::recursive_mutex &, std::recursive_mutex >", "structbdm_1_1type__ternary__operator.html", null ],
    [ "bdm::type_ternary_operator<is_same< Backend, bdm::SoaRef >::value, std::vector< size_t > &, std::vector< size_t > >", "structbdm_1_1type__ternary__operator.html", null ],
    [ "bdm::type_ternary_operator<true, T, U >", "structbdm_1_1type__ternary__operator_3true_00_01T_00_01U_01_4.html", null ],
    [ "bdm::Uniform", "structbdm_1_1Uniform.html", null ],
    [ "bdm::UniqueEventIdFactory", "classbdm_1_1UniqueEventIdFactory.html", null ],
    [ "bdm::Variant< Types >", "classbdm_1_1Variant.html", null ],
    [ "bdm::VectorPlaceholder< T >", "classbdm_1_1VectorPlaceholder.html", null ],
    [ "bdm::Param::VisualizeDiffusion", "structbdm_1_1Param_1_1VisualizeDiffusion.html", null ],
    [ "bdm::detail::WriteContainerFunctor< TSoSimBackend, TBackend >", "structbdm_1_1detail_1_1WriteContainerFunctor.html", null ]
];