name: Website CI

on:
  schedule:
    # Every day at 3 am
    - cron: '0 3 * * *'
  push:
    branches:
      - github-actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz make
        curl -L -O https://github.com/Kitware/CMake/releases/download/v3.17.3/cmake-3.17.3-Linux-x86_64.sh
        chmod +x cmake-3.17.3-Linux-x86_64.sh
        sudo ./cmake-3.17.3-Linux-x86_64.sh --skip-license --prefix=/usr/local

    - name: Set OSVERS
      run: echo "::set-env name=OSVERS::$(lsb_release -si)-$(lsb_release -sr)"

    - name: Cache pyenv
      uses: actions/cache@v2
      id: pyenv-cache
      with:
        path: ~/.pyenv
        key: ${{ env.OSVERS }}-pyenv-3.6.9

    - name: Install pyenv dependency
      if: steps.pyenv-cache.outputs.cache-hit != 'true'
      run: |
        curl https://pyenv.run | bash
        export PATH="$HOME/.pyenv/bin:$PATH"
        eval "$(pyenv init -)"
        PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install 3.6.9
        pyenv shell 3.6.9

    - name: Checkout BioDynaMo
      uses: actions/checkout@v2
      with:
        repository: BioDynaMo/biodynamo
        fetch-depth: 0

    - name: Cache Third Party Packages
      uses: actions/cache@v2
      with:
        path: build/third_party
        key: ${{ env.OSVERS }}-third-party-${{ hashFiles('cmake/external/SHA256Digests.cmake') }}

    - name: Build biodynamo.org
      shell: bash
      run: |
        cmake \
          -Dwebsite=on \
          -B build
        cd build
        make website

    - name: Deploy biodynamo.org
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_branch: master
        user_name: 'github-actions[bot]'
        user_email: 'bdm.travis@cern.ch'
        publish_dir: ./build/website/public
        cname: biodynamo.org

    - name: Notify Slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        author_name: Integration Test
        fields: repo,ref,message,author,action,workflow # default: repo,commit
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # optional
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      if: always() # Pick up events even if the job fails or is canceled.
