# This Github Actions Workflow checks out the latest version of the BioDynaMo
# master branch and builds the website biodynamo.org with the build target `website`.
# Internally it relies on the Gatsby framework to generate the static files
name: Website CI

on:
  schedule:
    # Every day at 3 am
    - cron: '0 3 * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz make
        curl -L -O https://github.com/Kitware/CMake/releases/download/v3.17.3/cmake-3.17.3-Linux-x86_64.sh
        chmod +x cmake-3.17.3-Linux-x86_64.sh
        sudo ./cmake-3.17.3-Linux-x86_64.sh --skip-license --prefix=/usr/local

    - name: Set OSVERS
      run: echo "OSVERS=$(lsb_release -si)-$(lsb_release -sr)" >> $GITHUB_ENV

    - name: Cache pyenv
      uses: actions/cache@v2
      id: pyenv-cache
      with:
        path: ~/.pyenv
        key: ${{ env.OSVERS }}-pyenv-3.8.0

    - name: Install pyenv dependency
      if: steps.pyenv-cache.outputs.cache-hit != 'true'
      run: |
        curl https://pyenv.run | bash
        export PATH="$HOME/.pyenv/bin:$PATH"
        eval "$(pyenv init -)"
        PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install 3.8.0
        pyenv shell 3.8.0

    - name: Checkout BioDynaMo
      uses: actions/checkout@v2
      with:
        repository: BioDynaMo/biodynamo
        fetch-depth: 0

    - name: Cache Third Party Packages
      uses: actions/cache@v2
      with:
        path: build/third_party
        key: ${{ env.OSVERS }}-third-party-${{ hashFiles('cmake/external/SHA256Digests.cmake') }}

    - name: Install prerequisites
      shell: bash
      run: |
        util/installation/ubuntu-16.04/prerequisites.sh all

    - name: Build biodynamo.org
      shell: bash
      run: |
        cmake \
          -Dwebsite=on \
          -Dtest=off \
          -Dnotebooks=on \
          -B build
        cd build
        make -j4
        make website

    # Since the deploy step below deletes all website files first, before adding
    # the updated files, it will also delete the .github folder
    # We copy the .github folder to the publish_dir, so that it will be re-added
    # once we deploy
    - name: Copy Github Actions workflow
      run: cp -R .github ./build/website/public

    - name: Deploy biodynamo.org
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_branch: master
        user_name: 'github-actions[bot]'
        user_email: 'bdm.travis@cern.ch'
        publish_dir: ./build/website/public
        cname: biodynamo.org
        exclude_assets: ''

    - name: Notify Slack
      uses: 8398a7/action-slack@v3
      with:
        status: custom
        fields: workflow,job,commit,repo,ref,author,took,message
        custom_payload: |
          {
            username: 'GitHub CI',
            icon_emoji: ':octocat:',
            attachments: [{
              color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
              text: `${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} ${{ job.status }} in ${process.env.AS_TOOK}\n${process.env.AS_MESSAGE}`
            }]
          }
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # optional
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      if: always() # Pick up events even if the job fails or is canceled.
